# Generated by Django 3.2.12 on 2022-03-28 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='company_details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='qualification',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='responsibility',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=200, null=True),
        ),
    ]
