# Generated by Django 3.2.12 on 2022-03-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0002_auto_20220328_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobdetail',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='jobdetail',
            name='responsibility',
        ),
    ]
