# Generated by Django 3.2.12 on 2022-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0004_remove_jobdetail_company_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='jobdetail',
            name='type',
        ),
    ]
