# Generated by Django 3.2.12 on 2022-03-28 11:46

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0005_auto_20220328_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='company_details',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company_logo',
            field=models.ImageField(blank=True, default='defaultlogo.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=200, null=True),
        ),
    ]
