# Generated by Django 3.2.12 on 2022-03-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0006_auto_20220328_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobDetail',
        ),
    ]
