# Generated by Django 3.2.12 on 2022-03-28 11:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0007_delete_jobdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=200, null=True)),
                ('salary', models.CharField(max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('responsibility', ckeditor.fields.RichTextField()),
                ('qualification', ckeditor.fields.RichTextField()),
                ('published_date', models.DateField(max_length=200, null=True)),
                ('deadline_date', models.DateField(max_length=200, null=True)),
                ('no_of_vaccinies', models.CharField(max_length=200, null=True)),
                ('company_details', ckeditor.fields.RichTextField()),
                ('company_logo', models.ImageField(blank=True, default='defaultlogo.png', null=True, upload_to='')),
            ],
        ),
    ]
