# Generated by Django 3.2.12 on 2022-03-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0010_alter_jobdetail_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='company_logo',
            field=models.ImageField(blank=True, default='defaultlogo.png', null=True, upload_to='company_logo'),
        ),
    ]
