# Generated by Django 3.2.12 on 2022-04-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findingJob', '0012_alter_jobdetail_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='company_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='qualification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='responsibility',
            field=models.TextField(),
        ),
    ]
