# Generated by Django 3.2.12 on 2022-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0015_jobdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='jobcategory',
            field=models.ManyToManyField(to='findingJob.JobCategory'),
        ),
    ]
