# Generated by Django 3.2.12 on 2022-04-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findingJob', '0016_auto_20220403_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='jobcategory',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='jobcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findingJob.jobcategory'),
        ),
    ]
